version: "3.0"

expectations:
  population_size: 10000

actions:
  generate_study_population_1:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2018-01-01 to 2019-12-01 by month" --output-dir=output --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/input*.feather

  generate_study_population_2:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2020-01-01 to 2021-12-01 by month" --output-dir=output --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/input_*.feather

  generate_dose:
    run: python:latest python analysis/calculate_dose_scaled_back.py
    needs: [generate_study_population_1, generate_study_population_2]
    outputs:
      highly_sensitive:
        cohort: output/inpu*.feather
  
  #generate_study_population_ethnicity:
  #run: cohortextractor:latest generate_cohort --study-definition study_definition_ethnicity --output-dir=output --output-format=csv
  #outputs:
  #highly_sensitive:
  #cohort: output/input_ethnicity.csv

  #join_ethnicity:
  #run: python:latest python analysis/join_ethnicity.py
  #needs: [generate_study_population, generate_study_population_ethnicity]
  #outputs:
  #highly_sensitive:
  #cohort: output/input*.csv

  generate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition --output-dir=output
    needs: [generate_dose]
    outputs: 
      moderately_sensitive:
        measure_csv: output/measure_*_rate.csv

  generate_notebook:
    run: jupyter:latest jupyter nbconvert /workspace/analysis/report.ipynb --execute --to html --template basic --output-dir=/workspace/output --ExecutePreprocessor.timeout=86400 --no-input
    needs: [generate_measures]
    outputs:
      moderately_sensitive:
        notebook: output/report.html
        plots: output/*.png
        tables: output/*.csv
  #generate_dose_match:
  #run: python:latest python analysis/dose_match.py
  #needs: [generate_measures]
  #outputs:
  #moderately_sensitive:
  #figure: output/dose_match.png
