version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2021-01-01 to 2021-04-01 by month" --output-dir=output --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input_*.csv.gz

  generate_study_population_ethnicity:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ethnicity --output-dir=output --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/input_ethnicity.csv

  generate_study_population_creatinine_clearance:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_creatinine_clearance --output-dir=output --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/input_creatinine_clearance.csv

  join_ethnicity:
    run: python:latest python analysis/join_ethnicity.py
    needs: [generate_study_population, generate_study_population_ethnicity]
    outputs:
      highly_sensitive:
        cohort: output/input*.csv.gz

  generate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition --output-dir=output
    needs: [join_ethnicity]
    outputs:
        moderately_sensitive:
          measure_csv: output/measure_*.csv.gz

  # join_doac_dose
  # join_creatinine_clearances