version: "3.0"

expectations:
  population_size: 10000

actions:
  generate_study_population_1:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2018-01-01 to 2019-12-01 by month" --output-dir=output --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/input*.feather

  generate_study_population_2:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2020-01-01 to 2022-06-01 by month" --output-dir=output --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/input_*.feather
  
  generate_study_population_3:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2022-07-01 to 2024-03-01 by month" --output-dir=output --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/inp*.feather


  generate_dose:
    run: python:latest python analysis/calculate_dose_scaled_back.py
    needs: [generate_study_population_1, generate_study_population_2, generate_study_population_3]
    outputs:
      highly_sensitive:
        cohort: output/inpu*.feather
  
  filter_population:
    run: python:latest python analysis/filter_population.py
    needs: [generate_dose]
    outputs:
      highly_sensitive:
        cohort: output/filtered/input*.feather
  
  generate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition --output-dir=output/filtered
    needs: [filter_population]
    outputs: 
      moderately_sensitive:
        measure_csv: output/filtered/measure_*_rate.csv

  round_measures:
    run: python:latest python analysis/round_measures.py
    needs: [generate_measures]
    outputs:
      moderately_sensitive:
        measure_csv: output/filtered/measure_*rate.csv

  generate_plots:
    run: python:v2 python analysis/report.py
    needs: [round_measures]
    outputs:
      moderately_sensitive:
        plots: output/filtered/*.png
        tables: output/filtered/*.csv

  # to be run localy
  generate_notebook_local:
    run: jupyter:latest jupyter nbconvert /workspace/analysis/report_local.ipynb --execute --to html --template basic --output-dir=/workspace/released_outputs --ExecutePreprocessor.timeout=86400 --no-input
    needs: [round_measures]
    outputs:
      moderately_sensitive:
        notebook: released_outputs/report_local.html
  