version: "3.0"

expectations:
  population_size: 10000

actions:
  generate_study_population_1:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2018-01-01 to 2019-12-01 by month" --output-dir=output --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/input*.feather

  generate_study_population_2:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2020-01-01 to 2022-06-01 by month" --output-dir=output --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/input_*.feather
  
  generate_study_population_3:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2022-07-01 to 2023-09-01 by month" --output-dir=output --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/inp*.feather


  generate_dose:
    run: python:latest python analysis/calculate_dose_scaled_back.py
    needs: [generate_study_population_1, generate_study_population_2, generate_study_population_3]
    outputs:
      highly_sensitive:
        cohort: output/inpu*.feather
  
  filter_population:
    run: python:latest python analysis/filter_population.py
    needs: [generate_dose]
    outputs:
      highly_sensitive:
        cohort: output/filtered/input*.feather
  
  generate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition --output-dir=output/filtered
    needs: [filter_population]
    outputs: 
      moderately_sensitive:
        measure_csv: output/filtered/measure_*_rate.csv